// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace Azure.IoT.DeviceUpdate.Models
{
    internal partial class DeploymentDeviceStatesList
    {
        internal static DeploymentDeviceStatesList DeserializeDeploymentDeviceStatesList(JsonElement element)
        {
            IReadOnlyList<DeploymentDeviceState> value = default;
            Optional<string> nextLink = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("value"))
                {
                    List<DeploymentDeviceState> array = new List<DeploymentDeviceState>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(DeploymentDeviceState.DeserializeDeploymentDeviceState(item));
                    }
                    value = array;
                    continue;
                }
                if (property.NameEquals("nextLink"))
                {
                    nextLink = property.Value.GetString();
                    continue;
                }
            }
            return new DeploymentDeviceStatesList(value, nextLink.Value);
        }
    }
}
