// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace Azure.IoT.DeviceUpdate.Models
{
    /// <summary> The DeploymentRetryAction. </summary>
    public readonly partial struct DeploymentRetryAction : IEquatable<DeploymentRetryAction>
    {
        private readonly string _value;

        /// <summary> Initializes a new instance of <see cref="DeploymentRetryAction"/>. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public DeploymentRetryAction(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string RetryValue = "retry";

        /// <summary> Retry action. </summary>
        public static DeploymentRetryAction Retry { get; } = new DeploymentRetryAction(RetryValue);
        /// <summary> Determines if two <see cref="DeploymentRetryAction"/> values are the same. </summary>
        public static bool operator ==(DeploymentRetryAction left, DeploymentRetryAction right) => left.Equals(right);
        /// <summary> Determines if two <see cref="DeploymentRetryAction"/> values are not the same. </summary>
        public static bool operator !=(DeploymentRetryAction left, DeploymentRetryAction right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="DeploymentRetryAction"/>. </summary>
        public static implicit operator DeploymentRetryAction(string value) => new DeploymentRetryAction(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is DeploymentRetryAction other && Equals(other);
        /// <inheritdoc />
        public bool Equals(DeploymentRetryAction other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
