// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace Azure.IoT.DeviceUpdate.Models
{
    /// <summary> The DeploymentCancelAction. </summary>
    public readonly partial struct DeploymentCancelAction : IEquatable<DeploymentCancelAction>
    {
        private readonly string _value;

        /// <summary> Initializes a new instance of <see cref="DeploymentCancelAction"/>. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public DeploymentCancelAction(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string CancelValue = "cancel";

        /// <summary> Cancel action. </summary>
        public static DeploymentCancelAction Cancel { get; } = new DeploymentCancelAction(CancelValue);
        /// <summary> Determines if two <see cref="DeploymentCancelAction"/> values are the same. </summary>
        public static bool operator ==(DeploymentCancelAction left, DeploymentCancelAction right) => left.Equals(right);
        /// <summary> Determines if two <see cref="DeploymentCancelAction"/> values are not the same. </summary>
        public static bool operator !=(DeploymentCancelAction left, DeploymentCancelAction right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="DeploymentCancelAction"/>. </summary>
        public static implicit operator DeploymentCancelAction(string value) => new DeploymentCancelAction(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is DeploymentCancelAction other && Equals(other);
        /// <inheritdoc />
        public bool Equals(DeploymentCancelAction other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
