// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Azure.IoT.DeviceUpdate.Models
{
    /// <summary> Deployment metadata. </summary>
    public partial class Deployment
    {
        /// <summary> Initializes a new instance of Deployment. </summary>
        /// <param name="deploymentId"> The deployment identifier. </param>
        /// <param name="startDateTime"> The deployment start datetime. </param>
        /// <param name="updateId"> Update identity. </param>
        /// <param name="groupId"> The group identity. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="deploymentId"/>, <paramref name="updateId"/> or <paramref name="groupId"/> is null. </exception>
        public Deployment(string deploymentId, DateTimeOffset startDateTime, UpdateId updateId, string groupId)
        {
            if (deploymentId == null)
            {
                throw new ArgumentNullException(nameof(deploymentId));
            }
            if (updateId == null)
            {
                throw new ArgumentNullException(nameof(updateId));
            }
            if (groupId == null)
            {
                throw new ArgumentNullException(nameof(groupId));
            }

            DeploymentId = deploymentId;
            StartDateTime = startDateTime;
            UpdateId = updateId;
            GroupId = groupId;
        }

        /// <summary> Initializes a new instance of Deployment. </summary>
        /// <param name="deploymentId"> The deployment identifier. </param>
        /// <param name="startDateTime"> The deployment start datetime. </param>
        /// <param name="updateId"> Update identity. </param>
        /// <param name="groupId"> The group identity. </param>
        /// <param name="isCanceled"> Boolean flag indicating whether the deployment was canceled. </param>
        /// <param name="isRetried"> Boolean flag indicating whether the deployment has been retried. </param>
        internal Deployment(string deploymentId, DateTimeOffset startDateTime, UpdateId updateId, string groupId, bool? isCanceled, bool? isRetried)
        {
            DeploymentId = deploymentId;
            StartDateTime = startDateTime;
            UpdateId = updateId;
            GroupId = groupId;
            IsCanceled = isCanceled;
            IsRetried = isRetried;
        }

        /// <summary> The deployment identifier. </summary>
        public string DeploymentId { get; set; }
        /// <summary> The deployment start datetime. </summary>
        public DateTimeOffset StartDateTime { get; set; }
        /// <summary> Update identity. </summary>
        public UpdateId UpdateId { get; set; }
        /// <summary> The group identity. </summary>
        public string GroupId { get; set; }
        /// <summary> Boolean flag indicating whether the deployment was canceled. </summary>
        public bool? IsCanceled { get; set; }
        /// <summary> Boolean flag indicating whether the deployment has been retried. </summary>
        public bool? IsRetried { get; set; }
    }
}
