// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Azure.IoT.DeviceUpdate.Models
{
    /// <summary> Deployment status metadata. </summary>
    public partial class DeploymentStatus
    {
        /// <summary> Initializes a new instance of DeploymentStatus. </summary>
        /// <param name="deploymentState"> The state of the deployment. </param>
        internal DeploymentStatus(DeploymentState deploymentState)
        {
            DeploymentState = deploymentState;
        }

        /// <summary> Initializes a new instance of DeploymentStatus. </summary>
        /// <param name="deploymentState"> The state of the deployment. </param>
        /// <param name="totalDevices"> The total number of devices in the deployment. </param>
        /// <param name="devicesInProgressCount"> The number of devices that are currently in deployment. </param>
        /// <param name="devicesCompletedFailedCount"> The number of devices that have completed deployment with a failure. </param>
        /// <param name="devicesCompletedSucceededCount"> The number of devices which have successfully completed deployment. </param>
        /// <param name="devicesCanceledCount"> The number of devices which have had their deployment canceled. </param>
        internal DeploymentStatus(DeploymentState deploymentState, int? totalDevices, int? devicesInProgressCount, int? devicesCompletedFailedCount, int? devicesCompletedSucceededCount, int? devicesCanceledCount)
        {
            DeploymentState = deploymentState;
            TotalDevices = totalDevices;
            DevicesInProgressCount = devicesInProgressCount;
            DevicesCompletedFailedCount = devicesCompletedFailedCount;
            DevicesCompletedSucceededCount = devicesCompletedSucceededCount;
            DevicesCanceledCount = devicesCanceledCount;
        }

        /// <summary> The state of the deployment. </summary>
        public DeploymentState DeploymentState { get; }
        /// <summary> The total number of devices in the deployment. </summary>
        public int? TotalDevices { get; }
        /// <summary> The number of devices that are currently in deployment. </summary>
        public int? DevicesInProgressCount { get; }
        /// <summary> The number of devices that have completed deployment with a failure. </summary>
        public int? DevicesCompletedFailedCount { get; }
        /// <summary> The number of devices which have successfully completed deployment. </summary>
        public int? DevicesCompletedSucceededCount { get; }
        /// <summary> The number of devices which have had their deployment canceled. </summary>
        public int? DevicesCanceledCount { get; }
    }
}
