// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;

namespace Azure.IoT.DeviceUpdate.Models
{
    /// <summary> Device class metadata. </summary>
    public partial class DeviceClass
    {
        /// <summary> Initializes a new instance of DeviceClass. </summary>
        /// <param name="deviceClassId"> The device class identifier. </param>
        /// <param name="compatProperties"> The compat properties of the device class. This object can be thought of as a set of key-value pairs where the key is the name of the compatibility property and the value is the value of the compatibility property. There will always be at least 1 compat property. </param>
        /// <param name="bestCompatibleUpdateId"> Update identity. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="deviceClassId"/> or <paramref name="compatProperties"/> is null. </exception>
        internal DeviceClass(string deviceClassId, IReadOnlyDictionary<string, string> compatProperties, UpdateId bestCompatibleUpdateId)
        {
            if (deviceClassId == null)
            {
                throw new ArgumentNullException(nameof(deviceClassId));
            }
            if (compatProperties == null)
            {
                throw new ArgumentNullException(nameof(compatProperties));
            }

            DeviceClassId = deviceClassId;
            CompatProperties = compatProperties;
            BestCompatibleUpdateId = bestCompatibleUpdateId;
        }

        /// <summary> The device class identifier. </summary>
        public string DeviceClassId { get; }
        /// <summary> The compat properties of the device class. This object can be thought of as a set of key-value pairs where the key is the name of the compatibility property and the value is the value of the compatibility property. There will always be at least 1 compat property. </summary>
        public IReadOnlyDictionary<string, string> CompatProperties { get; }
        /// <summary> Update identity. </summary>
        public UpdateId BestCompatibleUpdateId { get; }
    }
}
