// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace Azure.IoT.DeviceUpdate.Models
{
    public partial class DeviceUpdateAgentId : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            writer.WritePropertyName("deviceId");
            writer.WriteStringValue(DeviceId);
            if (Optional.IsDefined(ModuleId))
            {
                writer.WritePropertyName("moduleId");
                writer.WriteStringValue(ModuleId);
            }
            writer.WriteEndObject();
        }

        internal static DeviceUpdateAgentId DeserializeDeviceUpdateAgentId(JsonElement element)
        {
            string deviceId = default;
            Optional<string> moduleId = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("deviceId"))
                {
                    deviceId = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("moduleId"))
                {
                    moduleId = property.Value.GetString();
                    continue;
                }
            }
            return new DeviceUpdateAgentId(deviceId, moduleId.Value);
        }
    }
}
