// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Azure.IoT.DeviceUpdate.Models
{
    /// <summary> Device Update agent id. </summary>
    public partial class DeviceUpdateAgentId
    {
        /// <summary> Initializes a new instance of DeviceUpdateAgentId. </summary>
        /// <param name="deviceId"> Device Id. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="deviceId"/> is null. </exception>
        public DeviceUpdateAgentId(string deviceId)
        {
            if (deviceId == null)
            {
                throw new ArgumentNullException(nameof(deviceId));
            }

            DeviceId = deviceId;
        }

        /// <summary> Initializes a new instance of DeviceUpdateAgentId. </summary>
        /// <param name="deviceId"> Device Id. </param>
        /// <param name="moduleId"> Module Id. </param>
        internal DeviceUpdateAgentId(string deviceId, string moduleId)
        {
            DeviceId = deviceId;
            ModuleId = moduleId;
        }

        /// <summary> Device Id. </summary>
        public string DeviceId { get; set; }
        /// <summary> Module Id. </summary>
        public string ModuleId { get; set; }
    }
}
