// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace Azure.IoT.DeviceUpdate.Models
{
    public partial class DeviceClass
    {
        internal static DeviceClass DeserializeDeviceClass(JsonElement element)
        {
            string deviceClassId = default;
            IReadOnlyDictionary<string, string> compatProperties = default;
            UpdateId bestCompatibleUpdateId = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("deviceClassId"))
                {
                    deviceClassId = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("compatProperties"))
                {
                    Dictionary<string, string> dictionary = new Dictionary<string, string>();
                    foreach (var property0 in property.Value.EnumerateObject())
                    {
                        dictionary.Add(property0.Name, property0.Value.GetString());
                    }
                    compatProperties = dictionary;
                    continue;
                }
                if (property.NameEquals("bestCompatibleUpdateId"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        bestCompatibleUpdateId = null;
                        continue;
                    }
                    bestCompatibleUpdateId = UpdateId.DeserializeUpdateId(property.Value);
                    continue;
                }
            }
            return new DeviceClass(deviceClassId, compatProperties, bestCompatibleUpdateId);
        }
    }
}
