// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace Azure.IoT.DeviceUpdate.Models
{
    /// <summary> The ImportAction. </summary>
    public readonly partial struct ImportAction : IEquatable<ImportAction>
    {
        private readonly string _value;

        /// <summary> Initializes a new instance of <see cref="ImportAction"/>. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public ImportAction(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string ImportValue = "import";

        /// <summary> Import action. </summary>
        public static ImportAction Import { get; } = new ImportAction(ImportValue);
        /// <summary> Determines if two <see cref="ImportAction"/> values are the same. </summary>
        public static bool operator ==(ImportAction left, ImportAction right) => left.Equals(right);
        /// <summary> Determines if two <see cref="ImportAction"/> values are not the same. </summary>
        public static bool operator !=(ImportAction left, ImportAction right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="ImportAction"/>. </summary>
        public static implicit operator ImportAction(string value) => new ImportAction(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is ImportAction other && Equals(other);
        /// <inheritdoc />
        public bool Equals(ImportAction other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
