// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Azure.Core;

namespace Azure.IoT.DeviceUpdate.Models
{
    /// <summary> Import update input item metadata. </summary>
    public partial class ImportUpdateInputItem
    {
        /// <summary> Initializes a new instance of ImportUpdateInputItem. </summary>
        /// <param name="importManifest"> Import manifest metadata like source URL, file size/hashes, etc. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="importManifest"/> is null. </exception>
        public ImportUpdateInputItem(ImportManifestMetadata importManifest)
        {
            if (importManifest == null)
            {
                throw new ArgumentNullException(nameof(importManifest));
            }

            ImportManifest = importManifest;
            Files = new ChangeTrackingList<FileImportMetadata>();
        }

        /// <summary> Import manifest metadata like source URL, file size/hashes, etc. </summary>
        public ImportManifestMetadata ImportManifest { get; }
        /// <summary> Friendly update name. </summary>
        public string FriendlyName { get; set; }
        /// <summary> One or more update file properties like filename and source URL. </summary>
        public IList<FileImportMetadata> Files { get; }
    }
}
