// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace Azure.IoT.DeviceUpdate.Models
{
    public partial class InstallResult
    {
        internal static InstallResult DeserializeInstallResult(JsonElement element)
        {
            int resultCode = default;
            int extendedResultCode = default;
            Optional<string> resultDetails = default;
            Optional<IReadOnlyList<StepResult>> stepResults = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("resultCode"))
                {
                    resultCode = property.Value.GetInt32();
                    continue;
                }
                if (property.NameEquals("extendedResultCode"))
                {
                    extendedResultCode = property.Value.GetInt32();
                    continue;
                }
                if (property.NameEquals("resultDetails"))
                {
                    resultDetails = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("stepResults"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    List<StepResult> array = new List<StepResult>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(StepResult.DeserializeStepResult(item));
                    }
                    stepResults = array;
                    continue;
                }
            }
            return new InstallResult(resultCode, extendedResultCode, resultDetails.Value, Optional.ToList(stepResults));
        }
    }
}
