// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Linq;

namespace Azure.IoT.DeviceUpdate.Models
{
    /// <summary> The Instructions. </summary>
    public partial class Instructions
    {
        /// <summary> Initializes a new instance of Instructions. </summary>
        /// <param name="steps"> Collection of installation steps. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="steps"/> is null. </exception>
        internal Instructions(IEnumerable<Step> steps)
        {
            if (steps == null)
            {
                throw new ArgumentNullException(nameof(steps));
            }

            Steps = steps.ToList();
        }

        /// <summary> Initializes a new instance of Instructions. </summary>
        /// <param name="steps"> Collection of installation steps. </param>
        internal Instructions(IReadOnlyList<Step> steps)
        {
            Steps = steps;
        }

        /// <summary> Collection of installation steps. </summary>
        public IReadOnlyList<Step> Steps { get; }
    }
}
