// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace Azure.IoT.DeviceUpdate.Models
{
    public partial class Instructions
    {
        internal static Instructions DeserializeInstructions(JsonElement element)
        {
            IReadOnlyList<Step> steps = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("steps"))
                {
                    List<Step> array = new List<Step>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(Step.DeserializeStep(item));
                    }
                    steps = array;
                    continue;
                }
            }
            return new Instructions(steps);
        }
    }
}
