// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace Azure.IoT.DeviceUpdate.Models
{
    public partial class LogCollectionOperationDetailedStatus
    {
        internal static LogCollectionOperationDetailedStatus DeserializeLogCollectionOperationDetailedStatus(JsonElement element)
        {
            Optional<string> operationId = default;
            Optional<string> createdDateTime = default;
            Optional<string> lastActionDateTime = default;
            Optional<OperationStatus> status = default;
            Optional<IReadOnlyList<LogCollectionOperationDeviceStatus>> deviceStatus = default;
            Optional<string> description = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("operationId"))
                {
                    operationId = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("createdDateTime"))
                {
                    createdDateTime = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("lastActionDateTime"))
                {
                    lastActionDateTime = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("status"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    status = new OperationStatus(property.Value.GetString());
                    continue;
                }
                if (property.NameEquals("deviceStatus"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    List<LogCollectionOperationDeviceStatus> array = new List<LogCollectionOperationDeviceStatus>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(LogCollectionOperationDeviceStatus.DeserializeLogCollectionOperationDeviceStatus(item));
                    }
                    deviceStatus = array;
                    continue;
                }
                if (property.NameEquals("description"))
                {
                    description = property.Value.GetString();
                    continue;
                }
            }
            return new LogCollectionOperationDetailedStatus(operationId.Value, createdDateTime.Value, lastActionDateTime.Value, Optional.ToNullable(status), Optional.ToList(deviceStatus), description.Value);
        }
    }
}
