// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Linq;

namespace Azure.IoT.DeviceUpdate.Models
{
    /// <summary> The list of diagnostics operations with detailed status, with server paging support. </summary>
    internal partial class LogCollectionOperationDetailedStatusList
    {
        /// <summary> Initializes a new instance of LogCollectionOperationDetailedStatusList. </summary>
        /// <param name="value"> The collection of pageable items. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        internal LogCollectionOperationDetailedStatusList(IEnumerable<LogCollectionOperationDetailedStatus> value)
        {
            if (value == null)
            {
                throw new ArgumentNullException(nameof(value));
            }

            Value = value.ToList();
        }

        /// <summary> The collection of pageable items. </summary>
        public IReadOnlyList<LogCollectionOperationDetailedStatus> Value { get; }
        /// <summary> The link to the next page of items. </summary>
        public string NextLink { get; }
    }
}
