// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace Azure.IoT.DeviceUpdate.Models
{
    public partial class LogCollectionOperationDeviceStatus
    {
        internal static LogCollectionOperationDeviceStatus DeserializeLogCollectionOperationDeviceStatus(JsonElement element)
        {
            string deviceId = default;
            Optional<string> moduleId = default;
            OperationStatus status = default;
            Optional<string> resultCode = default;
            Optional<string> extendedResultCode = default;
            Optional<string> logLocation = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("deviceId"))
                {
                    deviceId = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("moduleId"))
                {
                    moduleId = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("status"))
                {
                    status = new OperationStatus(property.Value.GetString());
                    continue;
                }
                if (property.NameEquals("resultCode"))
                {
                    resultCode = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("extendedResultCode"))
                {
                    extendedResultCode = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("logLocation"))
                {
                    logLocation = property.Value.GetString();
                    continue;
                }
            }
            return new LogCollectionOperationDeviceStatus(deviceId, moduleId.Value, status, resultCode.Value, extendedResultCode.Value, logLocation.Value);
        }
    }
}
