// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Azure.IoT.DeviceUpdate.Models
{
    /// <summary> The step result under an update. </summary>
    public partial class StepResult
    {
        /// <summary> Initializes a new instance of StepResult. </summary>
        /// <param name="resultCode"> Install result code. </param>
        /// <param name="extendedResultCode"> Install extended result code. </param>
        internal StepResult(int resultCode, int extendedResultCode)
        {
            ResultCode = resultCode;
            ExtendedResultCode = extendedResultCode;
        }

        /// <summary> Initializes a new instance of StepResult. </summary>
        /// <param name="updateId"> It is update id for update steps; otherwise it is null. </param>
        /// <param name="description"> Step description. It might be null for update steps. </param>
        /// <param name="resultCode"> Install result code. </param>
        /// <param name="extendedResultCode"> Install extended result code. </param>
        /// <param name="resultDetails"> A string containing further details about the install result. </param>
        internal StepResult(UpdateId updateId, string description, int resultCode, int extendedResultCode, string resultDetails)
        {
            UpdateId = updateId;
            Description = description;
            ResultCode = resultCode;
            ExtendedResultCode = extendedResultCode;
            ResultDetails = resultDetails;
        }

        /// <summary> It is update id for update steps; otherwise it is null. </summary>
        public UpdateId UpdateId { get; }
        /// <summary> Step description. It might be null for update steps. </summary>
        public string Description { get; }
        /// <summary> Install result code. </summary>
        public int ResultCode { get; }
        /// <summary> Install extended result code. </summary>
        public int ExtendedResultCode { get; }
        /// <summary> A string containing further details about the install result. </summary>
        public string ResultDetails { get; }
    }
}
