// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using Azure.Core;

namespace Azure.IoT.DeviceUpdate.Models
{
    /// <summary> Update install instruction step. </summary>
    public partial class Step
    {
        /// <summary> Initializes a new instance of Step. </summary>
        internal Step()
        {
            Files = new ChangeTrackingList<string>();
        }

        /// <summary> Initializes a new instance of Step. </summary>
        /// <param name="type"> Step type. </param>
        /// <param name="description"> Step description. </param>
        /// <param name="handler"> Identity of handler that will execute this step. Required if step type is inline. </param>
        /// <param name="handlerProperties"> Parameters to be passed to handler during execution. </param>
        /// <param name="files"> Collection of file names to be passed to handler during execution. Required if step type is inline. </param>
        /// <param name="updateId"> Referenced child update identity.  Required if step type is reference. </param>
        internal Step(StepType? type, string description, string handler, object handlerProperties, IReadOnlyList<string> files, UpdateId updateId)
        {
            Type = type;
            Description = description;
            Handler = handler;
            HandlerProperties = handlerProperties;
            Files = files;
            UpdateId = updateId;
        }

        /// <summary> Step type. </summary>
        public StepType? Type { get; }
        /// <summary> Step description. </summary>
        public string Description { get; }
        /// <summary> Identity of handler that will execute this step. Required if step type is inline. </summary>
        public string Handler { get; }
        /// <summary> Parameters to be passed to handler during execution. </summary>
        public object HandlerProperties { get; }
        /// <summary> Collection of file names to be passed to handler during execution. Required if step type is inline. </summary>
        public IReadOnlyList<string> Files { get; }
        /// <summary> Referenced child update identity.  Required if step type is reference. </summary>
        public UpdateId UpdateId { get; }
    }
}
