// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace Azure.IoT.DeviceUpdate.Models
{
    public partial class StepResult
    {
        internal static StepResult DeserializeStepResult(JsonElement element)
        {
            Optional<UpdateId> updateId = default;
            Optional<string> description = default;
            int resultCode = default;
            int extendedResultCode = default;
            Optional<string> resultDetails = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("updateId"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    updateId = UpdateId.DeserializeUpdateId(property.Value);
                    continue;
                }
                if (property.NameEquals("description"))
                {
                    description = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("resultCode"))
                {
                    resultCode = property.Value.GetInt32();
                    continue;
                }
                if (property.NameEquals("extendedResultCode"))
                {
                    extendedResultCode = property.Value.GetInt32();
                    continue;
                }
                if (property.NameEquals("resultDetails"))
                {
                    resultDetails = property.Value.GetString();
                    continue;
                }
            }
            return new StepResult(updateId.Value, description.Value, resultCode, extendedResultCode, resultDetails.Value);
        }
    }
}
