// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Azure.IoT.DeviceUpdate.Models
{
    /// <summary> Update filter. </summary>
    internal partial class UpdateFilter
    {
        /// <summary> Initializes a new instance of UpdateFilter. </summary>
        internal UpdateFilter()
        {
        }

        /// <summary> Update isDeployable property. </summary>
        public bool? IsDeployable { get; }
    }
}
